services:
  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: yarn run start:dev products
    env_file:
      - ./apps/products/.env
    ports:
     - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth: 
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    env_file:
      - ./apps/auth/.env    
    ports:
     - '3001:3001'
    volumes:
      - .:/usr/src/app
  rabbitmq :
     image: rabbitmq
     ports:
      - 5672:5672   
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  
